version: '3'

services:
  app:
    image: 'highload:latest'
    build:
      context: .
    container_name: highload
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/highload?schema=auth
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=User_123

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=User_123
      - POSTGRES_DB=highload
    volumes:
#   раскомментировать для монтирования локального каталога для хранения данных
#     - ./<postgres-data>:/var/lib/postgresql/data
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
