server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 1000
#  error:
#    whitelabel:
#      enabled: false

spring:
  application:
    name: highload
  flyway:
    enabled: true
    locations: classpath:db/migrations
  datasource:
    driverClassname: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/highload?currentSchema=auth
    username: postgres
    password: User_123
    hikari:
      maximum-pool-size: 300
      minimum-idle: 10

management:
  metrics:
    tags:
      application: highload
    distribution:
      percentiles-histogram:
        http.server.requests: true
  server:
    port: 8088
    servlet:
      context-path: /
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
      path-mapping:
        metrics: metrics_names
        prometheus: metrics

jwt:
  key: 12345678
  exp: 120
